SRCDIR  := src
INCLDIR := include

WRAPPEDNATIVE_SRC := $(SRCDIR)/MPintWrappedNativePimple.cpp
WRAPPEDNATIVE_HDR := $(INCLDIR)/MPint.hpp

GMP_SRC           := $(SRCDIR)/MPintGMPPimple.cpp
GMP_HDR           := $(INCLDIR)/MPint.hpp


DEMO_DIR := demo

DEMO_SRCDIR  := $(DEMO_DIR)/src
DEMO_INCLDIR := $(DEMO_DIR)/src
DEMO_BINDIR  := $(DEMO_DIR)/bin

DEMO_SRCS := $(DEMO_SRCDIR)/demo.cpp $(DEMO_SRCDIR)/exprTest.cpp $(DEMO_SRCDIR)/det.cpp $(DEMO_SRCDIR)/redu.cpp $(DEMO_SRCDIR)/demoUtils.cpp
DEMO_HDRS := $(DEMO_INCLDIR)/det.hpp $(DEMO_INCLDIR)/redu.hpp $(DEMO_INCLDIR)/demoUtils.hpp $(DEMO_INCLDIR)/demoTypedef.hpp $(DEMO_INCLDIR)/exprTest.hpp


TARGET_NATIVE        := $(DEMO_BINDIR)/demoNative
TARGET_GMPXX         := $(DEMO_BINDIR)/demoGMPXX
TARGET_WRAPPEDNATIVEPIMPLE := $(DEMO_BINDIR)/demoWrappedNativePimple
TARGET_GMPPIMPLE           := $(DEMO_BINDIR)/demoGMPPimple

TARGETS := $(TARGET_NATIVE) $(TARGET_GMPXX) $(TARGET_WRAPPEDNATIVEPIMPLE) $(TARGET_GMPPIMPLE)


TEST_DIR := test

TESTOUTPUT_NATIVE             := $(TEST_DIR)/demoNative.output
TESTOUTPUT_GMPXX              := $(TEST_DIR)/demoGMPXX.output
TESTOUTPUT_WRAPPEDNATIVEPIMPLE := $(TEST_DIR)/demoWrappedNativePimple.output
TESTOUTPUT_GMPPIMPLE          := $(TEST_DIR)/demoGMPPimple.output

TESTOUTPUTS := $(TESTOUTPUT_NATIVE) $(TESTOUTPUT_GMPXX) $(TESTOUTPUT_WRAPPEDNATIVEPIMPLE) $(TESTOUTPUT_GMPPIMPLE)


CXX      := g++
CXXFLAGS := -std=c++14 -Wall -Wextra -pedantic -Werror -O2 -flto=auto


.PHONY: all clean

all: $(TARGETS)

clean:
	$(RM) $(TARGETS) $(TESTOUTPUTS)


$(TARGET_NATIVE): $(DEMO_SRCS) $(DEMO_HDRS)
	$(CXX) $(CXXFLAGS) -DDEMO_NATIVE -I$(DEMO_INCLDIR) -o $@ $(DEMO_SRCS)

$(TARGET_GMPXX): $(DEMO_SRCS) $(DEMO_HDRS)
	$(CXX) $(CXXFLAGS) -DDEMO_GMPXX -I$(DEMO_INCLDIR) -o $@ $(DEMO_SRCS) -lgmp -lgmpxx

$(TARGET_WRAPPEDNATIVEPIMPLE): $(DEMO_SRCS) $(DEMO_HDRS) $(WRAPPEDNATIVE_SRC) $(WRAPPEDNATIVE_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_WRAPPEDNATIVEPIMPLE -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS) $(WRAPPEDNATIVE_SRC)

$(TARGET_GMPPIMPLE): $(DEMO_SRCS) $(DEMO_HDRS) $(GMP_SRC) $(GMP_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_GMPPIMPLE -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS)  $(GMP_SRC) -lgmp
