SRCDIR  := src
INCLDIR := include


WRAPPEDNATIVE_HDR      := $(INCLDIR)/MPintWrappedNative.hpp

WRAPPEDNATIVEPIMPL_SRC := $(SRCDIR)/MPintWrappedNativePimpl.cpp
WRAPPEDNATIVEPIMPL_HDR := $(INCLDIR)/MPintPimpl.hpp

GMP_HDR                := $(INCLDIR)/MPintGMP.hpp

GMPPIMPL_SRC           := $(SRCDIR)/MPintGMPPimpl.cpp
GMPPIMPL_HDR           := $(INCLDIR)/MPintPimpl.hpp


DEMO_DIR := demo

DEMO_SRCDIR  := $(DEMO_DIR)/src
DEMO_INCLDIR := $(DEMO_DIR)/src
DEMO_BINDIR  := $(DEMO_DIR)/bin

DEMO_SRCS := $(DEMO_SRCDIR)/demo.cpp $(DEMO_SRCDIR)/exprTest.cpp $(DEMO_SRCDIR)/det.cpp $(DEMO_SRCDIR)/redu.cpp $(DEMO_SRCDIR)/demoUtils.cpp
DEMO_HDRS := $(DEMO_INCLDIR)/det.hpp $(DEMO_INCLDIR)/redu.hpp $(DEMO_INCLDIR)/demoUtils.hpp $(DEMO_INCLDIR)/demoTypedef.hpp $(DEMO_INCLDIR)/exprTest.hpp


TARGET_NATIVE             := $(DEMO_BINDIR)/demoNative
TARGET_GMPXX              := $(DEMO_BINDIR)/demoGMPXX
TARGET_WRAPPEDNATIVE      := $(DEMO_BINDIR)/demoWrappedNative
TARGET_WRAPPEDNATIVEPIMPL := $(DEMO_BINDIR)/demoWrappedNativePimpl
TARGET_GMP                := $(DEMO_BINDIR)/demoGMP
TARGET_GMPPIMPL           := $(DEMO_BINDIR)/demoGMPPimpl

TARGETS := $(TARGET_NATIVE) $(TARGET_GMPXX) $(TARGET_WRAPPEDNATIVE) $(TARGET_WRAPPEDNATIVEPIMPL) $(TARGET_GMP) $(TARGET_GMPPIMPL)


TEST_DIR := test

TESTOUTPUT_NATIVE             := $(TEST_DIR)/demoNative.output
TESTOUTPUT_GMPXX              := $(TEST_DIR)/demoGMPXX.output
TESTOUTPUT_WRAPPEDNATIVE      := $(TEST_DIR)/demoWrappedNative.output
TESTOUTPUT_WRAPPEDNATIVEPIMPL := $(TEST_DIR)/demoWrappedNativePimpl.output
TESTOUTPUT_GMP                := $(TEST_DIR)/demoGMP.output
TESTOUTPUT_GMPPIMPL           := $(TEST_DIR)/demoGMPPimpl.output

TESTOUTPUTS := $(TESTOUTPUT_NATIVE) $(TESTOUTPUT_GMPXX) $(TESTOUTPUT_WRAPPEDNATIVE) $(TESTOUTPUT_WRAPPEDNATIVEPIMPL) $(TESTOUTPUT_GMP) $(TESTOUTPUT_GMPPIMPL)


CXX      := g++
CXXFLAGS := -std=c++14 -Wall -Wextra -pedantic -Werror -O2 -flto=auto


.PHONY: all clean

all: $(TARGETS)

clean:
	$(RM) $(TARGETS) $(TESTOUTPUTS)


$(TARGET_NATIVE): $(DEMO_SRCS) $(DEMO_HDRS)
	$(CXX) $(CXXFLAGS) -DDEMO_NATIVE -I$(DEMO_INCLDIR) -o $@ $(DEMO_SRCS)

$(TARGET_GMPXX): $(DEMO_SRCS) $(DEMO_HDRS)
	$(CXX) $(CXXFLAGS) -DDEMO_GMPXX -I$(DEMO_INCLDIR) -o $@ $(DEMO_SRCS) -lgmp -lgmpxx

$(TARGET_WRAPPEDNATIVE): $(DEMO_SRCS) $(DEMO_HDRS) $(WRAPPEDNATIVE_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_WRAPPEDNATIVE -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS)

$(TARGET_WRAPPEDNATIVEPIMPL): $(DEMO_SRCS) $(DEMO_HDRS) $(WRAPPEDNATIVEPIMPL_SRC) $(WRAPPEDNATIVEPIMPL_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_WRAPPEDNATIVEPIMPL -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS) $(WRAPPEDNATIVEPIMPL_SRC)

$(TARGET_GMP): $(DEMO_SRCS) $(DEMO_HDRS) $(GMP_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_GMP -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS) -lgmp

$(TARGET_GMPPIMPL): $(DEMO_SRCS) $(DEMO_HDRS) $(GMPPIMPL_SRC) $(GMPPIMPL_HDR)
	$(CXX) $(CXXFLAGS) -DDEMO_GMPPIMPL -I$(DEMO_INCLDIR) -I$(INCLDIR) -o $@ $(DEMO_SRCS)  $(GMPPIMPL_SRC) -lgmp
